# Caroselli e grafiche singole di novembre-dicembre. Le citazioni sono testuali dalle Puntate 1
# (download/*.epub): *parola* = parola in ambra. `python carousel.py` rende le slide,
# `python carousel.py --calendar` aggiunge le voci a ../calendar.json.
CTA = "Puntata 1 gratis in PDF ed EPUB, senza iscrizione: link in bio."
BUG, OBL = "Il Bug della Trasparenza", "L’Economia dell’Oblio"
Q = lambda text, **kw: dict(k="quote", text=text, **kw)
END = dict(k="cta")


def single(id, when, book, seg, slide, caption, tags, alt, theme=None):
    return dict(id=id, when=when, book=book, seg=seg, slides=[slide], caption=caption, tags=tags, alt=alt, theme=theme)


def story(id, when, book, seg, slide):
    return dict(id=id, when=when, book=book, seg=seg, slides=[slide], story=True)


ITEMS = [

 # ---------- presentazione (30 settembre) ----------
 single("p00-presentazione", "2026-09-30T12:30", "bug", "Presentazione dell’autore + tutti",
  dict(k="covers", text="Ciao, sono *D. Iasio*. Scrivo *romanzi*.", items=[("bug", "Il silenzio è finito. La verità è *pubblica*."), ("oblio", "Chi dimentica diventa *innocente*. Paga solo chi ricorda.")]),
  "Ciao, sono D. Iasio. Scrivo romanzi noir e thriller.\nPer ora escono a puntate, una sera alla volta: Il Bug della Trasparenza (noir sociale, otto puntate) e L’Economia dell’Oblio (thriller psicologico, sei). Spero presto di poterli offrire interi negli store.\nQui trovi estratti, dietro le quinte e le date delle prossime puntate. La Puntata 1 di entrambi è gratis, in PDF o EPUB, senza iscrizione: link in bio.",
  "#noir #thrillerpsicologico #narrativaitaliana #romanzi #autoreemergente",
  "Le copertine dei due romanzi, Il Bug della Trasparenza e L’Economia dell’Oblio, con la scritta «Ciao, sono D. Iasio. Scrivo romanzi.»"),
 # ---------- caroselli (domenica 20:00, e giovedì 3 dicembre) ----------
 dict(id="c01-oblio-listino", when="2026-11-29T20:00", book="oblio", seg="Fantascienza/distopia + satira del lavoro (carosello)",
  slides=[dict(k="hook", kick=OBL, text="Quanto vale un *dolore*?", sub="Il listino di uno studio di estrazioni. Scorri."),
          dict(k="rows", title="STUDIO LEVIA · PORTA ROMANA", sub="LISTINO ESTRAZIONI",
               rows=[("Lutto pulito", "€ 4.000"), ("Tradimento medio", "€ 1.500"), ("Vergogna", "€ 900"), ("Cotta non ricambiata", "€ 60")],
               note="Una cotta non ricambiata vale sessanta euro: «roba da minorenni»."),
          Q("Il dolore è l’unica materia prima che la gente produce *gratis*, ogni giorno, in quantità industriali."),
          Q("Il lutto pulito è il *bitcoin* dei ricordi."),
          Q("Il mio lavoro, spiegato a mia madre in quattro parole, è questo: il cliente pensa a una cosa, io la trovo, la taglio, la metto in una *scatola*.", who="Dora Calvi · tecnica estrattiva"),
          END],
  caption="Il listino dello studio dove lavora Dora Calvi. Scorri: i prezzi, il mercato e il modo in cui si taglia un ricordo. Tutto dal romanzo.\nLevia e i suoi prezzi sono immaginari. La sensazione che tutto abbia un costo, un po’ meno.\n" + CTA,
  tags="#thrillerpsicologico #distopia #satira #fantascienza #narrativaitaliana",
  alt="Carosello di sei slide su fondo scuro: il listino dello studio Levia (lutto pulito 4000 euro, tradimento medio 1500, vergogna 900, cotta non ricambiata 60), tre citazioni e l’invito a leggere la Puntata 1 de L’Economia dell’Oblio."),
 dict(id="c05-bug-o-oblio", when="2026-12-03T12:30", book="bug", seg="Community (commenti) + lettori di noir e thriller",
  slides=[dict(k="hook", kick="Due romanzi a puntate", text="Quale *comincerai* per primo?", sub="La Puntata 1 di entrambi è gratis. Scorri e scegli."),
          dict(k="covers", text="Due domande. Due *romanzi*.", items=[("bug", "E se il tuo condominio leggesse i tuoi *pensieri*?"), ("oblio", "E se il *dolore* si potesse vendere?")]),
          Q("Ogni palazzo nasconde più cose di quante ne mostri. La differenza, di solito, è solo chi ha le *chiavi* giuste.", who=BUG + " · Puntata 1"),
          Q("Il dolore è un *costo*. E i costi si tagliano.", book="oblio", who=OBL + " · Puntata 1"),
          dict(k="cta", books=["bug", "oblio"], text="Dimmelo nei *commenti*.", line="Puntata 1 gratis · PDF ed EPUB · <b>libri.diasio.ch</b>")],
  caption="Bug o Oblio? Un noir sociale in otto puntate contro un thriller psicologico in sei. Quale cominceresti per primo? Dimmelo nei commenti: leggo tutto.\n" + CTA,
  tags="#noir #thrillerpsicologico #narrativaitaliana #bookstagram #libriconsigliati",
  alt="Carosello di cinque slide: la domanda «Quale comincerai per primo?», le copertine de Il Bug della Trasparenza e L’Economia dell’Oblio con una domanda ciascuna, due citazioni e l’invito a leggere la Puntata 1 di entrambi."),
 dict(id="c02-bug-assemblea", when="2026-12-06T20:00", book="bug", seg="Vita di condominio + tech/privacy + lettori noir",
  slides=[dict(k="hook", kick=BUG, text="Assemblea. Ore *19:00*. Punto quattro.", sub="La scena che apre il romanzo, in cinque frasi. Scorri."),
          Q("Il punto quattro è una formalità. […] Lo approviamo per *acclamazione* e andiamo avanti, che alle venti ho una cena.", who="Cesare Rocchi Molteni, presidente"),
          Q("Meridiana Life si è *aggiornata*. Benvenuti in Trasparenza Meridiana.", who="La notifica, su tutti i telefoni"),
          Q("Il preventivo B mi sembra il più serio. Prezzo onesto, tempi ragionevoli.", who="Cesare Rocchi Molteni, presidente"),
          Q("Il preventivo B è di mio *cognato*. Se lo dico gli altri capiscono e mi tolgono la presidenza.", who="Il post senza nome · 19:41"),
          Q("Il tipo di *silenzio* che in una stanza con quaranta persone si sente fisicamente, come una pressione sui timpani."),
          END],
  caption="Dieci minuti di assemblea di condominio e un bug che dice la verità. Le frasi della scena che apre Il Bug della Trasparenza, nell’ordine in cui succedono.\nTu quale punto all’ordine del giorno salteresti?\n" + CTA,
  tags="#noir #thrillersociale #condominio #privacy #narrativaitaliana",
  alt="Carosello di sette slide su fondo scuro con le frasi dell’assemblea di condominio de Il Bug della Trasparenza: la formalità del punto quattro, la notifica dell’aggiornamento, il preventivo B, il post che rivela il cognato, il silenzio in sala."),
 dict(id="c03-oblio-pettine", when="2026-12-13T20:00", book="oblio", seg="Fantascienza/distopia (fan di serie come Black Mirror)",
  slides=[dict(k="hook", kick=OBL, text="Il *Pettine*.", sub="Ogni sei mesi ti scansionano il cervello. Scorri."),
          Q("Ogni sei mesi ti mettono in una stanza bianca, ti scansionano il cervello e cercano il *trasudo*: ricordi degli altri rimasti attaccati, schegge, tracce.", who="Il Pettine"),
          Q("Lo chiamano *Certificazione di Vuoto*, che è un nome da rito religioso e dice già tutto.", who="Il Pettine"),
          Q("Se sei pulita ti danno un buono benessere da *quaranta euro* e una pacca sulla spalla.", who="Il Pettine"),
          Q("Se trovano roba, ti sospendono e ti fanno il *Reset*, che è la parola gentile per cancellarti l’intera memoria episodica, dall’asilo in su.", who="Il Pettine"),
          Q("Ho un ricordo che non voglio e una firma che non ricordo. Uno dei due sta mentendo, e sto cominciando a sospettare che sia la *mia testa*.", who="Dora Calvi"),
          END],
  caption="Il Pettine è il controllo semestrale obbligatorio per chi lavora con i ricordi degli altri. Se trovano tracce, ti resettano.\nPer chi ama le distopie che sembrano a un passo da noi. Scorri fino all’ultima frase.\n" + CTA,
  tags="#distopia #fantascienza #blackmirror #thrillerpsicologico #narrativaitaliana",
  alt="Carosello di sette slide su fondo scuro: come funziona il Pettine, il controllo semestrale della memoria, la Certificazione di Vuoto, il Reset e la frase finale di Dora Calvi. L’Economia dell’Oblio."),
 dict(id="c06-natale-albero", when="2026-12-20T20:00", book="bug", seg="Lettori digitali + regalo di Natale + serie a puntate",
  slides=[dict(k="hook", kick="Sotto l’albero", text="Un regalo che non costa *niente*.", sub="Due romanzi a puntate. La Puntata 1 di entrambi è gratis."),
          dict(k="covers", text="Da leggere una *sera* alla volta.", items=[("bug", "Un condominio d’élite, un’app che sa *troppo*."), ("oblio", "Un mercato che compra il *dolore*.")]),
          dict(k="hook", text="PDF, EPUB, *Kindle*.", sub="Nessuna iscrizione per leggere la Puntata 1. Scarichi il file e cominci."),
          dict(k="hook", text="Buone *feste*.", sub="Una sera alla volta, anche a Natale."),
          dict(k="cta", books=["bug", "oblio"], text="La Puntata 1 di *entrambi*.", line="PDF ed EPUB · <b>libri.diasio.ch</b>")],
  caption="Se cerchi qualcosa da leggere nelle sere di festa: la Puntata 1 di entrambi i romanzi è gratis, in PDF o EPUB (va bene anche su Kindle). Nessuna iscrizione.\nSe conosci qualcuno che ama noir e thriller, basta girargli il link.\nLink in bio.",
  tags="#ebook #kindle #epub #leggeregratis #narrativaitaliana",
  alt="Carosello di cinque slide: un regalo che non costa niente, le copertine dei due romanzi, i formati PDF ed EPUB, gli auguri di buone feste e l’invito a leggere la Puntata 1 di entrambi."),
 dict(id="c04-tre-passi", when="2026-12-27T20:00", book="bug", seg="Lettori digitali (ebook) + nuovi arrivati",
  slides=[dict(k="hook", kick="Come si legge", text="La Puntata 1, in *tre passi*.", sub="Gratis. Senza iscrizione. Scorri."),
          dict(k="step", n="1", title="Apri *libri.diasio.ch*", text="Dal link in bio, da telefono o da computer."),
          dict(k="step", n="2", title="Scegli il *romanzo*", text="*Il Bug della Trasparenza*, noir sociale in otto puntate. Oppure *L’Economia dell’Oblio*, thriller psicologico in sei."),
          dict(k="step", n="3", title="Scarica *PDF* o *EPUB*", text="Va bene anche su Kindle. Nessuna iscrizione richiesta."),
          dict(k="step", n="+", kick="Facoltativo", title="Una mail *quando esce* la prossima storia", text="Iscriviti alla newsletter dalla stessa pagina. Niente rumore."),
          END],
  caption="Come leggere la Puntata 1 in tre passi, per chi arriva adesso: si scarica, si legge, e se piace si decide se continuare.\nÈ gratis, in PDF o EPUB, e non serve iscriversi. Link in bio.",
  tags="#ebook #kindle #epub #leggeregratis #narrativaitaliana",
  alt="Carosello di sei slide: come leggere gratis la Puntata 1 in tre passi (aprire libri.diasio.ch, scegliere il romanzo, scaricare PDF o EPUB) e la newsletter facoltativa."),

 # ---------- grafiche singole (martedì 19:30 e giovedì 12:30) ----------
 single("d01-oblio-sei-minuti", "2026-12-01T19:30", "oblio", "Psicologia/memoria (tono rispettoso) + lettori thriller",
  Q("Ecco cos’è, il suo «lutto». Non il padre morto: quei *sei minuti*."),
  "Dora Calvi, davanti a un cliente che vuole dimenticare un lutto, vede che cosa sta davvero togliendo.\nIl romanzo parla di questo: cosa resta di noi quando ci togliamo ciò che fa male.\n" + CTA,
  "#thrillerpsicologico #memoria #psicologia #narrativaitaliana #bookstagram",
  "Citazione su fondo scuro: «Ecco cos’è, il suo lutto. Non il padre morto: quei sei minuti.» L’Economia dell’Oblio."),
 single("d02-oblio-fascicolo", "2026-12-08T19:30", "oblio", "Fantascienza/distopia + lettori thriller",
  dict(k="rows", title="FASCICOLO PERSONALE · D. CALVI", sub="ESTRAZIONI A PROPRIO CARICO: 1",
       rows=[("Data", "11 mesi e 3 giorni fa"), ("Contenuto", "[OSCURATO]"), ("Consenso informato", "FIRMATO"), ("Compenso", "nessuno"), ("Destinazione del lotto", "NON REGISTRATA")],
       note="La firma è la mia, fino all’ultima lettera. Solo che la D ha un ricciolo."),
  "Nel terminale della direzione, Dora Calvi trova una riga che non aveva mai guardato, perché nessuno guarda le righe che non pensa di avere.\nLa firma è sua. Il ricordo, no.\n" + CTA,
  "#thrillerpsicologico #distopia #fantascienza #narrativaitaliana #libriconsigliati",
  "Finto fascicolo personale di Dora Calvi: un’estrazione a proprio carico, contenuto oscurato, consenso firmato, compenso nessuno, destinazione del lotto non registrata. L’Economia dell’Oblio."),
 single("d03-bug-meridiana", "2026-12-10T12:30", "bug", "Tech/privacy + lettori noir", 
  Q("Meridiana Life. Icona azzurro pallido, una M stilizzata che sembrava un *sorriso rovesciato*."),
  "L’app del condominio, vista da chi ci abita: apre il cancello, prenota la palestra, manda le notifiche dei pacchi. Serve per tutto, finché una sera comincia a dire la verità.\n" + CTA,
  "#noir #thriller #privacy #tecnologia #narrativaitaliana",
  "Citazione su fondo ambra: «Meridiana Life. Icona azzurro pallido, una M stilizzata che sembrava un sorriso rovesciato.» Il Bug della Trasparenza.", theme="amber"),
 single("d04-oblio-pieghe", "2026-12-15T19:30", "oblio", "Psicologia/memoria + fantascienza",
  Q("Un ricordo tuo ha le *pieghe*: è stato usato, ripiegato, schiacciato sotto altri ricordi."),
  "Come si distingue un ricordo tuo da uno che ti hanno messo dentro? Dora Calvi ha un test, ed è vietato.\n" + CTA,
  "#thrillerpsicologico #memoria #distopia #fantascienza #narrativaitaliana",
  "Citazione su fondo scuro: «Un ricordo tuo ha le pieghe: è stato usato, ripiegato, schiacciato sotto altri ricordi.» L’Economia dell’Oblio."),
 single("d05-bug-istruttiva", "2026-12-17T12:30", "bug", "Lettori noir (core) + dialoghi",
  Q("«Bella serata, no?»\n«Molto *istruttiva*.»", who="Yusuf e Nadia, dopo l’assemblea"),
  "Il portiere e la giornalista, nell’atrio, dopo la serata in cui il condominio ha scoperto l’app. Nessuno dei due dice quello che pensa.\n" + CTA,
  "#noir #thriller #narrativaitaliana #bookstagram #libriconsigliati",
  "Dialogo su fondo scuro: «Bella serata, no?» «Molto istruttiva.» Il Bug della Trasparenza."),
 single("d06-oblio-regolatevi", "2026-12-22T19:30", "oblio", "Lettori thriller + voce narrante",
  Q("Quello che vi racconto lo racconto io. *Regolatevi* di conseguenza.", who="Dora Calvi, voce narrante", ),
  "Una narratrice che ti avvisa subito: la storia è la sua versione. Regolati di conseguenza.\n" + CTA,
  "#thrillerpsicologico #narrativaitaliana #bookstagram #libriconsigliati #distopia",
  "Citazione su fondo ambra: «Quello che vi racconto lo racconto io. Regolatevi di conseguenza.» L’Economia dell’Oblio.", theme="amber"),
 single("d07-buone-feste", "2026-12-24T12:30", "bug", "Tutti + Svizzera italiana",
  dict(k="hook", text="Buone *feste*.", sub="Una storia da leggere una sera alla volta. La Puntata 1 è gratis."),
  "Buone feste a chi legge, a chi commenta e a chi è arrivato da poco. Se avete una sera libera, la Puntata 1 vi aspetta: gratis, in PDF o EPUB, senza iscrizione.\nLink in bio.",
  "#ticino #svizzeraitaliana #narrativaitaliana #noir #thrillerpsicologico",
  "Grafica scura con la scritta «Buone feste. Una storia da leggere una sera alla volta. La Puntata 1 è gratis.»"),
 single("d08-bug-nel-dubbio", "2026-12-29T19:30", "bug", "Lettori noir (core) + tech",
  Q("L’app, in fondo, era stata progettata apposta perché nessuno restasse a lungo nel *dubbio*.", who="L’ultima riga della Puntata 1"),
  "L’ultima riga della Puntata 1 de Il Bug della Trasparenza. Da lì in poi, ogni puntata è una sera in più nel palazzo.\n" + CTA,
  "#noir #thriller #narrativaitaliana #tecnologia #libriconsigliati",
  "Citazione su fondo ambra: «L’app, in fondo, era stata progettata apposta perché nessuno restasse a lungo nel dubbio.» Il Bug della Trasparenza.", theme="amber"),
 single("d09-buon-anno", "2026-12-31T12:30", "bug", "Newsletter + tutti",
  dict(k="hook", text="Buon *2027*.", sub="Una mail quando esce la prossima storia. Iscriviti alla newsletter: link in bio."),
  "L’ultimo giorno dell’anno, un solo invito: se vuoi sapere quando esce la prossima storia, iscriviti alla newsletter. Una mail alla volta, niente rumore. E la Puntata 1 di entrambi i romanzi resta gratis.\nLink in bio.",
  "#ticino #svizzeraitaliana #narrativaitaliana #noir #thrillerpsicologico",
  "Grafica scura con la scritta «Buon 2027. Una mail quando esce la prossima storia.»"),

 # ---------- Storie (lunedì 18:30, formato 1080x1920, senza didascalia) ----------
 story("s01-bug-ascensore", "2026-10-05T18:30", "bug", "Storia · Vita di condominio", Q("Nessuno la salutava per prima nell’*ascensore*.", who="Nadia, undici giorni dopo il trasloco")),
 story("s02-puntata1", "2026-10-12T18:30", "bug", "Storia · Invito alla Puntata 1", dict(k="cta", books=["bug", "oblio"], text="La Puntata 1 di *entrambi*.", line="Gratis · PDF ed EPUB · <b>libri.diasio.ch</b> · link in bio")),
 story("s03-oblio-cugino", "2026-10-19T18:30", "oblio", "Storia · Satira aziendale", Q("Tutti hanno un *cugino*. Nico ne ha almeno tre e nessuno di loro è mai stato visto.", who="Dora Calvi")),
 story("s04-bug-portiere", "2026-10-26T18:30", "bug", "Storia · Lettori noir", Q("Un uomo che apriva porte e non ne varcava mai nessuna che non gli fosse stata *indicata*.", who="Yusuf, il portiere")),
 story("s05-due-romanzi", "2026-11-02T18:30", "bug", "Storia · Presentazione", dict(k="hook", kick="D. Iasio", text="Due romanzi. *Una sera* alla volta.", sub="La Puntata 1 è gratis. Link in bio.")),
 story("s06-oblio-stia-fermo", "2026-11-09T18:30", "oblio", "Storia · Umorismo nero", Q("«Bella frase. Stia *fermo*, per favore.»", who="Dora Calvi, al cliente")),
 story("s07-bug-cronista", "2026-11-16T18:30", "bug", "Storia · Giornalismo d’inchiesta", Q("Nadia li catalogò tutti, uno per uno, con la stessa *freddezza* con cui otto anni prima avrebbe catalogato le fonti di un’inchiesta.")),
 story("s08-puntata1-bis", "2026-11-23T18:30", "oblio", "Storia · Invito alla Puntata 1", dict(k="cta", books=["bug", "oblio"], text="Senza *iscrizione*.", line="La Puntata 1 è gratis · <b>libri.diasio.ch</b> · link in bio")),
 story("s09-oblio-mercato", "2026-11-30T18:30", "oblio", "Storia · Satira", Q("Il mercato è il *mercato*.", who="Nico")),
 story("s10-bug-non-ancora", "2026-12-07T18:30", "bug", "Storia · Lettori noir", Q("Non lo chiese. Non *ancora*.", who="Nadia, dopo la risposta del portiere")),
 story("s11-newsletter", "2026-12-14T18:30", "bug", "Storia · Newsletter", dict(k="hook", kick="Newsletter", text="Una mail *quando esce* la prossima storia.", sub="Iscriviti dal link in bio. Niente rumore.")),
 story("s12-feste", "2026-12-21T18:30", "oblio", "Storia · Feste", dict(k="hook", text="Per le sere *lunghe*.", sub="La Puntata 1 di entrambi i romanzi è gratis. Link in bio.")),
 story("s13-oblio-innocente", "2026-12-28T18:30", "oblio", "Storia · Lettori thriller", Q("Chi dimentica diventa *innocente*. Paga solo chi ricorda.", who="L’Economia dell’Oblio")),

 # ---------- Il Bug in evidenza, ora su Amazon Kindle (1 ottobre, immagine in alto come il post del 30/9) ----------
 dict(id="b01-bug-amazon", when="2026-10-01T19:00", book="bug", seg="Il Bug in evidenza: ora su Amazon Kindle (carosello)",
  slides=[dict(k="quote", hero=480, text="«Nessuno chiese di *leggere* le note di rilascio.»"),
          dict(k="hook", hero=650, kick="La premessa", text="L’app apre il cancello. Prenota la palestra. Fa *votare*.", sub="Poi arriva l’aggiornamento. Da quel momento l’app *ascolta*."),
          dict(k="quote", hero=900, text="«Un’unica scossa collettiva, come se il palazzo avesse un *battito cardiaco* e per un istante fosse saltato un colpo.»"),
          dict(k="quote", hero=(940, 1.45, 373), text="«Il tipo di silenzio che in una stanza con quaranta persone si sente fisicamente, come una *pressione sui timpani*.»"),
          dict(k="quote", hero=970, text="«Signora Colombo, ogni palazzo nasconde *più cose* di quante ne mostri.»", who="Yusuf Demir · il portiere"),
          dict(k="cta", text="Noir sociale · *otto puntate*", button="Ora su Amazon Kindle", line="Puntata 1 gratis, PDF ed EPUB · <b>libri.diasio.ch</b>")],
  caption="«Nessuno chiese di leggere le note di rilascio.»\n\nIn un condominio d’élite l’app di gestione riceve un aggiornamento obbligatorio. Da quel momento ascolta: quando qualcuno mente ad alta voce, il suo pensiero non filtrato compare davanti a tutti. Questa è una frase dalla Puntata 1.\n\nIl Bug della Trasparenza è un noir sociale in otto puntate, ora disponibile su Amazon Kindle. La Puntata 1 è gratis, in PDF o EPUB, senza iscrizione: link in bio.\n\nSalvalo se hai un vicino che sa troppo.",
  caption_fb="«Nessuno chiese di leggere le note di rilascio.»\n\nIn un condominio d’élite l’app di gestione riceve un aggiornamento obbligatorio. Da quel momento ascolta: quando qualcuno mente ad alta voce, il suo pensiero non filtrato compare davanti a tutti. Questa è una frase dalla Puntata 1.\n\nIl Bug della Trasparenza è un noir sociale in otto puntate, ora disponibile su Amazon Kindle: https://www.amazon.it/dp/B0HLN2VSJP\nLa Puntata 1 è gratis, in PDF o EPUB, senza iscrizione: https://libri.diasio.ch/bug/\n\n#noir #noirsociale #narrativaitaliana",
  tags="#noir #noirsociale #narrativaitaliana #bookstagram #kindle",
  alt="Carosello di sei slide su fondo scuro con la copertina de Il Bug della Trasparenza in alto: la frase «Nessuno chiese di leggere le note di rilascio», la premessa (l’app apre il cancello, prenota la palestra, fa votare, poi ascolta), tre citazioni dalla Puntata 1 e l’invito a leggerlo su Amazon Kindle."),
]
