# 24 post in ordine di pubblicazione. Le citazioni sono testuali dalle Puntate 1.
# seg = segmento di pubblico principale del post (vedi STRATEGIA.md)
BUG = "Il Bug della Trasparenza, Puntata 1"
OBL = "L’Economia dell’Oblio, Puntata 1"
CTA = "Puntata 1 gratis in PDF ed EPUB, senza iscrizione: link in bio."

POSTS = [
 dict(id="01-bug-hook-4piano", when="2026-10-04 20:00", seg="Vita di condominio + lettori noir", book="bug", kind="hook",
      text="L’app del condominio ha appena scritto la verità sul vicino del quarto.",
      sub="Nessuno può cancellarla. Nemmeno lui.",
      caption="Nel tuo condominio c’è un’app per tutto: cancello, pacchi, assemblee. Ora immagina che una sera cominci a dire la verità.\nIl Bug della Trasparenza è un noir a puntate ambientato in un palazzo dove tutti hanno qualcosa da nascondere. Poi arriva l’aggiornamento.\n" + CTA,
      tags="#noir #thriller #narrativaitaliana #condominio #libriconsigliati",
      alt="Grafica scura con la scritta: L’app del condominio ha appena scritto la verità sul vicino del quarto. Il Bug della Trasparenza, di D. Iasio."),
 dict(id="02-oblio-listino", when="2026-10-06 19:30", seg="Fantascienza/distopia + satira del lavoro", book="oblio", kind="hook",
      text="Un lutto pulito rende quattromila euro. Una vergogna, novecento.",
      sub="Il dolore si estrae e si vende. Lei lavora al terzo piano.",
      caption="In questo mondo il dolore è la materia prima più economica che esista. E c’è chi lo compra.\nL’Economia dell’Oblio è un thriller psicologico a puntate: una tecnica estrae i ricordi dei clienti e li mette in una scatola. Poi trova i frammenti di un omicidio nella propria testa.\n" + CTA,
      tags="#thrillerpsicologico #distopia #fantascienza #narrativaitaliana #bookstagram",
      alt="Grafica scura con la frase: Un lutto pulito rende quattromila euro. Una vergogna, novecento. L’Economia dell’Oblio, di D. Iasio."),
 dict(id="03-bug-cognato", when="2026-10-08 12:30", seg="Tech/privacy + giornalismo d’inchiesta", book="bug", kind="quote", who=BUG,
      text="Il preventivo B è di mio cognato. Se lo dico gli altri capiscono e mi tolgono la presidenza.",
      caption="Trasparenza totale: bello come slogan, un incubo quando tocca a te.\nUn bug nell’app del condominio e il presidente dell’assemblea si ritrova a dichiarare, senza volerlo, quello che stava per nascondere. Tutti i telefoni della sala lo leggono nello stesso momento.\n" + CTA,
      tags="#noir #thrillersociale #privacy #narrativaitaliana #libriconsigliati",
      alt="Citazione su fondo scuro: «Il preventivo B è di mio cognato. Se lo dico gli altri capiscono e mi tolgono la presidenza.» Il Bug della Trasparenza."),
 dict(id="04-oblio-domanda", when="2026-10-11 20:00", seg="Community di lettori (commenti) + psicologia/memoria", book="oblio", kind="hook",
      text="Se potessi vendere un ricordo, quale sarebbe?",
      sub="Nel romanzo un lutto pulito vale quattromila euro. Dimmelo nei commenti.",
      caption="Domanda della domenica sera: se qualcuno ti pagasse per togliere un ricordo dalla testa, quale sceglieresti? E lo faresti davvero?\nRispondi nei commenti, leggo tutto. Nel romanzo la scelta non è mai gratuita.\n" + CTA,
      tags="#thrillerpsicologico #memoria #distopia #bookstagram #leggere",
      alt="Grafica scura con la domanda: Se potessi vendere un ricordo, quale sarebbe? L’Economia dell’Oblio."),
 dict(id="05-oblio-costo", when="2026-10-13 19:30", seg="Mondo del lavoro e delle aziende", book="oblio", kind="quote", who=OBL,
      text="Il dolore è un costo. E i costi si tagliano.",
      caption="La frase preferita di un cliente che vuole «tagliare» il lutto del padre prima dell’assemblea dei soci.\nUna satira nera sul mondo in cui tutto ha un prezzo, anche quello che non dovrebbe averlo.\n" + CTA,
      tags="#thrillerpsicologico #distopia #satira #mondodellavoro #narrativaitaliana",
      alt="Citazione su fondo scuro: «Il dolore è un costo. E i costi si tagliano.» L’Economia dell’Oblio."),
 dict(id="06-bug-notifica", when="2026-10-15 12:30", seg="Tech/privacy/app", book="bug", kind="notif",
      kicker="AGGIORNAMENTO OBBLIGATORIO", text="Meridiana Life si è aggiornata. Benvenuti in Trasparenza Meridiana.",
      sub="Tutti i telefoni in sala vibrarono insieme.",
      caption="Nessuno legge le note di rilascio. Nessuno legge il regolamento. Ma tutti approvano per acclamazione.\nÈ così che comincia Il Bug della Trasparenza: con una notifica che non doveva essere un problema.\n" + CTA,
      tags="#privacy #tecnologia #thriller #noir #narrativaitaliana",
      alt="Finta notifica dell’app Meridiana Life: Meridiana Life si è aggiornata. Benvenuti in Trasparenza Meridiana. Il Bug della Trasparenza."),
 dict(id="07-bug-cta", when="2026-10-18 20:00", seg="Lettori digitali (ebook) + amanti delle serie a puntate", book="bug", kind="hook",
      text="Puntata 1 gratis. Il resto, una sera alla volta.",
      sub="PDF ed EPUB, senza iscrizione. Link in bio.",
      caption="Come una serie tv, ma da leggere: otto puntate, una sera alla volta.\nLa Puntata 1 de Il Bug della Trasparenza è gratis, in PDF o EPUB (va bene anche su Kindle). Nessuna iscrizione richiesta.\nLink in bio.",
      tags="#ebook #kindle #epub #leggeregratis #noir",
      alt="Grafica scura con la scritta: Puntata 1 gratis. Il resto, una sera alla volta. PDF ed EPUB, link in bio."),
 dict(id="08-oblio-levia", when="2026-10-20 19:30", seg="Tech/IA + pubblicità e brand", book="oblio", kind="brand", theme="amber",
      text="Levia.", tag="Il peso non è tuo.",
      sub="Lo slogan dell’azienda che estrae il dolore. L’Economia dell’Oblio, Puntata 1.",
      caption="Levia è il nome dell’azienda che, nel romanzo, ti toglie il dolore dalla testa. Lo slogan è tutto: «Il peso non è tuo».\nMa il peso non sparisce mai davvero. Qualcuno lo porta. Qualcuno lo compra.\n" + CTA,
      tags="#thrillerpsicologico #intelligenzaartificiale #distopia #fantascienza #narrativaitaliana",
      alt="Grafica ambra con la scritta Levia. Il peso non è tuo. Slogan dell’azienda immaginaria de L’Economia dell’Oblio."),
 dict(id="09-bug-chiavi", when="2026-10-22 12:30", seg="Lettori noir (core)", book="bug", kind="quote", who=BUG,
      text="Ogni palazzo nasconde più cose di quante ne mostri. La differenza, di solito, è solo chi ha le chiavi giuste.",
      caption="Il portiere sa più di quanto dice. In fondo al garage di Residenza Meridiana c’è una porta blindata senza targhetta che nessuno può aprire, a parte l’amministrazione.\n" + CTA,
      tags="#noir #thriller #narrativaitaliana #bookstagram #libriconsigliati",
      alt="Citazione su fondo scuro: «Ogni palazzo nasconde più cose di quante ne mostri. La differenza, di solito, è solo chi ha le chiavi giuste.» Il Bug della Trasparenza."),
 dict(id="10-bug-domanda", when="2026-10-25 20:00", seg="Community (commenti) + vita di condominio", book="bug", kind="hook",
      text="Se l’app del tuo condominio dicesse la verità, chi sarebbe il primo a finire nei guai?",
      sub="Nel romanzo è successo a un presidente. Rispondi nei commenti.",
      caption="Domanda della domenica sera, senza fare nomi: chi, nel tuo palazzo, avrebbe più da perdere se un’app dicesse tutto?\nSe vuoi sapere come va a finire per un presidente d’assemblea che «non ha alcun interesse personale», la Puntata 1 è gratis.\nLink in bio.",
      tags="#condominio #vicinidicasa #noir #thrillersociale #narrativaitaliana",
      alt="Grafica scura con la domanda: Se l’app del tuo condominio dicesse la verità, chi sarebbe il primo a finire nei guai? Il Bug della Trasparenza."),
 dict(id="11-oblio-bitcoin", when="2026-10-27 19:30", seg="Tech/finanza + fantascienza", book="oblio", kind="quote", who=OBL,
      text="Il lutto pulito è il bitcoin dei ricordi.",
      caption="Nel mondo di Dora Calvi i lutti si comprano, si vendono e si classificano: senza «se», senza «avrei dovuto». Quello con la colpa vale la metà.\n" + CTA,
      tags="#distopia #fantascienza #intelligenzaartificiale #thrillerpsicologico #narrativaitaliana",
      alt="Citazione su fondo scuro: «Il lutto pulito è il bitcoin dei ricordi.» L’Economia dell’Oblio."),
 dict(id="12-bug-note", when="2026-10-29 12:30", seg="Giornalismo d’inchiesta + scrittura/appunti", book="bug", kind="terminal",
      file="meridiana_note.txt",
      lines=[dict(t="15 del mese.", hot=True),
             dict(t="Aggiornamento attivato dal portiere su istruzione della gestione."),
             dict(t="Prima vittima: Cesare Rocchi Molteni, presidente, corruzione minore sul rifacimento tetto."),
             dict(t="Domanda aperta: chi altro, nel palazzo, sa già cosa succederà quando toccherà a loro?", hot=True)],
      caption="Nadia Colombo è una giornalista che non ha mai smesso di catalogare le persone. Le note del suo primo giorno nel palazzo sono tutto quello che ha, finché l’app non comincia a parlare.\nLe righe sono estratte dal finale della Puntata 1.\n" + CTA,
      tags="#giornalismo #inchiesta #noir #thriller #narrativaitaliana",
      alt="Finestra di un editor di testo con il file meridiana_note.txt: appunti della giornalista Nadia Colombo dopo la prima assemblea. Il Bug della Trasparenza."),
 dict(id="13-oblio-cta", when="2026-11-01 20:00", seg="Lettori digitali + Ognissanti/atmosfera thriller", book="oblio", kind="hook",
      text="Chi dimentica diventa innocente. Paga solo chi ricorda.",
      sub="Puntata 1 gratis in PDF ed EPUB. Link in bio.",
      caption="Per una sera di Ognissanti da thriller: «Chi dimentica diventa innocente. Paga solo chi ricorda.»\nLa Puntata 1 de L’Economia dell’Oblio è gratis, in PDF o EPUB. Sei puntate in tutto.\nLink in bio.",
      tags="#thrillerpsicologico #ebook #kindle #leggeregratis #distopia",
      alt="Grafica scura con la frase: Chi dimentica diventa innocente. Paga solo chi ricorda. L’Economia dell’Oblio, Puntata 1 gratis."),
 dict(id="14-bug-rimossa", when="2026-11-03 19:30", seg="Tech/privacy", book="bug", kind="quote", who=BUG,
      text="Trasparenza Meridiana non può essere rimossa da un singolo utente.",
      caption="C’è un’impostazione che non puoi disattivare da solo. E chi può disattivarla è proprio l’uomo che l’app ha appena smascherato.\nOgni tanto una funzione «per il tuo bene» ha un problema di controllo.\n" + CTA,
      tags="#privacy #tecnologia #noir #thriller #narrativaitaliana",
      alt="Citazione su fondo scuro: «Trasparenza Meridiana non può essere rimossa da un singolo utente.» Il Bug della Trasparenza."),
 dict(id="15-oblio-pettine", when="2026-11-05 12:30", seg="Fantascienza/distopia (fan di serie come Black Mirror)", book="oblio", kind="panel",
      title="CERTIFICAZIONE DI VUOTO",
      lines=["Ogni sei mesi ti scansionano il cervello.",
             "Cercano il trasudo: ricordi degli altri rimasti attaccati.",
             "Se sei pulita: un buono benessere da quaranta euro.",
             "Se trovano roba: il Reset. Memoria episodica cancellata, dall’asilo in su."],
      caption="Il Pettine: controllo semestrale obbligatorio per chi lavora con i ricordi degli altri. Se trovano tracce, ti resettano.\nPer chi ama le distopie che sembrano a un passo da noi.\n" + CTA,
      tags="#distopia #fantascienza #blackmirror #thrillerpsicologico #narrativaitaliana",
      alt="Grafica scura con il titolo Certificazione di Vuoto e quattro righe sulla scansione semestrale del cervello. L’Economia dell’Oblio."),
 dict(id="16-bug-spot", when="2026-11-08 20:00", seg="Bookstagram (copertina e presentazione)", book="bug", kind="spot",
      tag="Noir sociale · 8 puntate. Il silenzio è finito. La verità è pubblica.",
      caption="Il Bug della Trasparenza, di D. Iasio. Noir sociale in otto puntate: un condominio d’élite, un’app che non dovrebbe sapere quello che sa, una giornalista che ha un motivo per essere lì.\nLa Puntata 1 è gratis, in PDF o EPUB. Link in bio.",
      tags="#bookstagram #libriconsigliati #noir #narrativaitaliana #autoreemergente",
      alt="Copertina de Il Bug della Trasparenza: un palazzo notturno attraversato da frasi arancioni."),
 dict(id="17-oblio-strano", when="2026-11-10 19:30", seg="Psicologia/memoria (tono rispettoso)", book="oblio", kind="quote", who=OBL,
      text="Ho l’impressione di aver dimenticato qualcosa. Ma sto benissimo, eh. Benissimo.",
      caption="Il cliente esce più leggero e con la sensazione di aver perso qualcosa. Il romanzo parla di questo: cosa resta di noi quando ci togliamo ciò che fa male.\n" + CTA,
      tags="#thrillerpsicologico #memoria #psicologia #narrativaitaliana #bookstagram",
      alt="Citazione su fondo scuro: «Ho l’impressione di aver dimenticato qualcosa. Ma sto benissimo, eh. Benissimo.» L’Economia dell’Oblio."),
 dict(id="18-bug-regolamento", when="2026-11-12 12:30", seg="Umorismo di condominio + tech/consenso", book="bug", kind="quote", who=BUG, theme="amber",
      text="Il regolamento di condominio […] la definiva «strumento indispensabile alla vita comunitaria». Nessuno l’aveva letto fino in fondo. Nadia nemmeno.",
      caption="Lo strumento indispensabile, di cui nessuno ha letto i termini. Dai condomini alle app, cambia poco.\nTu li leggi, i regolamenti? Dimmelo nei commenti.\n" + CTA,
      tags="#condominio #privacy #noir #thriller #narrativaitaliana",
      alt="Citazione su fondo ambra: «Il regolamento di condominio la definiva strumento indispensabile alla vita comunitaria. Nessuno l’aveva letto fino in fondo. Nadia nemmeno.» Il Bug della Trasparenza."),
 dict(id="19-oblio-spot", when="2026-11-15 20:00", seg="Bookstagram (copertina e presentazione)", book="oblio", kind="spot",
      tag="Thriller psicologico · 6 puntate. Chi dimentica diventa innocente.",
      caption="L’Economia dell’Oblio, di D. Iasio. Thriller psicologico in sei puntate: una tecnica estrattiva, un mercato che compra il dolore, un omicidio che forse ha dentro la propria testa.\nLa Puntata 1 è gratis, in PDF o EPUB. Link in bio.",
      tags="#bookstagram #libriconsigliati #thrillerpsicologico #narrativaitaliana #autoreemergente",
      alt="Copertina de L’Economia dell’Oblio: il volto di una donna che si frantuma in schegge di vetro."),
 dict(id="20-bug-attivare", when="2026-11-17 19:30", seg="Mondo del lavoro (chi «esegue e basta»)", book="bug", kind="quote", who=BUG,
      text="Fa parte del mio lavoro attivare quello che mi dicono di attivare.",
      caption="Il classico «io eseguo». Un portiere, un’email con le istruzioni e un aggiornamento da attivare entro le sette.\nE se fosse questa la vera domanda del romanzo: chi risponde di ciò che fa il sistema?\n" + CTA,
      tags="#noir #thriller #mondodellavoro #narrativaitaliana #libriconsigliati",
      alt="Citazione su fondo scuro: «Fa parte del mio lavoro attivare quello che mi dicono di attivare.» Il Bug della Trasparenza."),
 dict(id="21-oblio-scontrino", when="2026-11-19 12:30", seg="Satira/lavoro + fantascienza", book="oblio", kind="receipt",
      title="STUDIO LEVIA · PORTA ROMANA", subtitle="LISTINO ESTRAZIONI",
      rows=[("Lutto pulito", "€ 4.000"), ("Tradimento medio", "€ 1.500"), ("Vergogna", "€ 900"), ("Cotta non ricambiata", "€ 60")],
      note="Il cliente pensa a una cosa, io la trovo, la taglio, la metto in una scatola.",
      caption="Il listino dello studio dove lavora Dora Calvi, tutto dal romanzo. Una cotta non ricambiata vale sessanta euro: «roba da minorenni».\nLevia e i suoi prezzi sono immaginari. La sensazione di riconoscerli un po’, molto meno.\n" + CTA,
      tags="#distopia #thrillerpsicologico #satira #fantascienza #narrativaitaliana",
      alt="Finto scontrino: listino dello studio Levia con lutto pulito 4000 euro, tradimento medio 1500, vergogna 900, cotta non ricambiata 60. L’Economia dell’Oblio."),
 dict(id="22-newsletter", when="2026-11-22 20:00", seg="Tutti + Svizzera italiana e Ticino", book="bug", kind="both",
      text="Una mail quando esce la prossima storia.",
      sub="Iscriviti alla newsletter: Puntata 1 gratis e novità in anteprima. Link in bio.",
      caption="Per chi legge in italiano dal Ticino, dalla Svizzera italiana, dall’Italia e ovunque: una mail solo quando esce la prossima storia, con qualche estratto. Niente rumore.\nLa Puntata 1 di entrambi i romanzi è gratis. Iscrizione dal link in bio.",
      tags="#ticino #svizzeraitaliana #narrativaitaliana #noir #thrillerpsicologico",
      alt="Le copertine dei due romanzi, Il Bug della Trasparenza e L’Economia dell’Oblio, con la scritta Una mail quando esce la prossima storia."),
 dict(id="23-oblio-igiene", when="2026-11-24 19:30", seg="Lettori noir/thriller (core)", book="oblio", kind="quote", who=OBL,
      text="Nessuno è pulito. Siamo tutti solo in ritardo con l’igiene.",
      caption="Nico, collega di Dora, sull’ossessione di essere «puliti» in un mondo in cui il passato si può togliere.\n" + CTA,
      tags="#thrillerpsicologico #distopia #narrativaitaliana #bookstagram #libriconsigliati",
      alt="Citazione su fondo scuro: «Nessuno è pulito. Siamo tutti solo in ritardo con l’igiene.» L’Economia dell’Oblio."),
 dict(id="24-oblio-regolamento", when="2026-11-26 12:30", seg="Lavoro/etica delle aziende + tech", book="oblio", kind="quote", who=OBL,
      text="Il regolamento dice che vedo «solo sagome, prive di contenuto emotivo». Il regolamento l’ha scritto un avvocato.",
      caption="Il regolamento dice una cosa, il lavoro un’altra. Dora Calvi vede dentro i ricordi dei clienti ogni giorno, e ha smesso di crederci.\n" + CTA,
      tags="#thrillerpsicologico #intelligenzaartificiale #distopia #narrativaitaliana #mondodellavoro",
      alt="Citazione su fondo scuro: «Il regolamento dice che vedo solo sagome, prive di contenuto emotivo. Il regolamento l’ha scritto un avvocato.» L’Economia dell’Oblio."),
]
